# Generated by Django 5.2.7 on 2025-11-01 18:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Função')),
                ('salario_mensal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Salário por função (R$)')),
            ],
        ),
        migrations.CreateModel(
            name='LavadorCargaEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavador', models.CharField(default='Lavador 2', editable=False, max_length=50)),
                ('data', models.DateField()),
                ('quantidade_caixas', models.PositiveIntegerField()),
                ('q_3A', models.PositiveIntegerField(default=0)),
                ('q_2A', models.PositiveIntegerField(default=0)),
                ('q_1A', models.PositiveIntegerField(default=0)),
                ('q_G', models.PositiveIntegerField(default=0)),
                ('valor_rendido', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor que rendeu da carreta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Tipo da Caixa')),
                ('tamanho', models.CharField(max_length=20, verbose_name='Tamanho')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de Produto')),
            ],
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mês (1-12)')),
                ('salario_total_funcionarios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frete', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refeicao_cafe', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Café da Manhã')),
                ('refeicao_almoco', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Almoço')),
                ('contabilidade', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'unique_together': {('ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('endereco', models.CharField(blank=True, max_length=250, verbose_name='Endereço')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='mvb.funcao')),
            ],
        ),
        migrations.CreateModel(
            name='LavagemCarreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Lavagem')),
                ('carreta_ident', models.CharField(blank=True, max_length=100, verbose_name='Identificador da Carreta')),
                ('quantidade_caixas', models.PositiveIntegerField(default=0)),
                ('valor_por_caixa', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tipo_caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mvb.tipocaixa')),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mvb.tipoproduto')),
            ],
        ),
        migrations.CreateModel(
            name='LavadorSujoEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavador', models.CharField(default='Lavador 1', editable=False, max_length=50)),
                ('data', models.DateField()),
                ('quantidade_caixas', models.PositiveIntegerField()),
                ('tamanho_caixa', models.CharField(max_length=10)),
                ('valor_por_caixa', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mvb.tipoproduto')),
            ],
        ),
    ]
