# Generated by Django 5.2.7 on 2025-11-02 15:06

import django.db.models.deletion
import mvb.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvb', '0002_funcionario_ativo_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lavadorcargaentry',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lavadorsujoentry',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lavagemcarreta',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='refeicao_almoco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Refeição - Almoço'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='refeicao_cafe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Refeição - Café da manhã'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[mvb.validators.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='lavagemcarreta',
            name='carreta_ident',
            field=models.CharField(blank=True, max_length=100, verbose_name='Identificador da carreta'),
        ),
    ]
