# Generated by Django 5.2.7 on 2025-11-11 23:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvb', '0004_cliente_bonuspayment_presenca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeiro',
            options={'ordering': ['-data', '-ano', '-mes']},
        ),
        migrations.AlterUniqueTogether(
            name='financeiro',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='data',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data do lançamento financeiro'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='ano',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='mes',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)]),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='refeicao_almoco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='refeicao_cafe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
