# Generated by Django 5.2.7 on 2025-11-14 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvb', '0005_alter_financeiro_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavadorcargaentry',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lavagens_carga', to='mvb.cliente'),
        ),
        migrations.AddField(
            model_name='lavadorcargaentry',
            name='tipo_lavagem',
            field=models.CharField(choices=[('sujo', 'Sujo'), ('carga', 'Por Carga')], default='carga', max_length=10),
        ),
        migrations.AddField(
            model_name='lavadorsujoentry',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lavagens_sujo', to='mvb.cliente'),
        ),
        migrations.AddField(
            model_name='lavadorsujoentry',
            name='tipo_lavagem',
            field=models.CharField(choices=[('sujo', 'Sujo'), ('carga', 'Por Carga')], default='sujo', max_length=10),
        ),
        migrations.AddField(
            model_name='lavagemcarreta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lavagens_carreta', to='mvb.cliente'),
        ),
        migrations.AddField(
            model_name='lavagemcarreta',
            name='tipo_lavagem',
            field=models.CharField(choices=[('sujo', 'Sujo'), ('carga', 'Por Carga')], default='sujo', max_length=10),
        ),
    ]
