# Generated by Django 5.2.7 on 2025-11-15 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvb', '0006_lavadorcargaentry_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='presenca',
            options={},
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='criado_por',
        ),
        migrations.RemoveField(
            model_name='presenca',
            name='presente',
        ),
        migrations.AddField(
            model_name='presenca',
            name='status',
            field=models.CharField(choices=[('P', 'Presente'), ('F', 'Falta'), ('O', 'Folga')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='presenca',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvb.funcionario'),
        ),
    ]
