# Generated by Django 5.2.7 on 2025-11-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvb', '0007_alter_presenca_options_remove_presenca_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
