# Generated by Django 5.2.7 on 2026-01-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvb', '0008_financeiro_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='ano',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='mes',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True),
        ),
    ]
