# Generated by Django 5.2.7 on 2026-01-17 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvb', '0009_alter_financeiro_ano_alter_financeiro_mes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeiro',
            options={'ordering': ['-data']},
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='ano',
            field=models.PositiveIntegerField(default=2025, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='mes',
            field=models.PositiveIntegerField(default=2025, editable=False),
            preserve_default=False,
        ),
    ]
