# Generated by Django 5.2.7 on 2026-01-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvb', '0010_alter_financeiro_options_alter_financeiro_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('F', 'Falta'), ('O', 'Folga')], default='A', max_length=1),
        ),
    ]
