# Generated by Django 5.2.7 on 2026-01-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvb', '0011_alter_presenca_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='status',
            field=models.CharField(choices=[('P', 'Presente'), ('F', 'Falta'), ('O', 'Folga')], default='A', max_length=1),
        ),
    ]
