# Generated by Django 5.2.7 on 2026-02-07 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvb', '0012_alter_presenca_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocaixa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoproduto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lavagemcarreta',
            name='carreta_ident',
            field=models.CharField(blank=True, max_length=100, verbose_name='Carreta (Nome Motorista)'),
        ),
        migrations.AlterField(
            model_name='lavagemcarreta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lavagens_carreta', to='mvb.cliente'),
        ),
    ]
